version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.1.0

    working_directory: ~/ccpv

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

      - persist_to_workspace:
          root: ~/
          paths: ./*

  build:
    docker:
      - image: circleci/node:10.1.0

    working_directory: ~/ccpv

    steps:
      - attach_workspace:
          at: ~/

      - run: npm run build

      - persist_to_workspace:
          root: ~/
          paths: ./*

workflows:
  version: 2

  test-and-build:
    jobs:
      - test

      - build:
          requires:
            - test
